apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: my-dev
  labels:
    app: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world-pod
        image: pawankumar34424.jfrog.io/default-docker-virtual/my-image:jenkins
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  namespace: my-dev
spec:
  selector:
    app: hello-world
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 35010
  type: LoadBalancer
