= Hello World with Docker and Kubernetes

This repo consists of a Spring Boot Hello World application. It shows:

. Run & test the application from CLI
. Create a Docker image, run the container and test it
. Create Kubernetes deployment and test it

Let's get started!

== CLI

=== Run App

```
mvn spring-boot:run
```

=== Test Application

```
curl http://localhost:8080
```

== Docker

=== Build Application

```
mvn clean package
```

=== Build Docker Image

```
docker image build -t arungupta/helloworld-spring-boot:latest .
```

=== Push Docker Image

```
docker image push arungupta/helloworld-spring-boot:latest
```

=== Run Docker Container

```
docker container run -d --name hello-world -p 8080:8080 arungupta/helloworld-spring-boot:latest
```

=== Test Application

```
curl http://localhost:8080
```

=== Delete Docker Container

```
docker container rm -f hello-world
```

== Kubernetes

=== Create Deployment

```
kubectl apply -f deployment.yaml
```

=== Test Application

```
curl http://`kubectl get svc hello-world-service -o jsonpath={.status.loadBalancer.ingress[0].hostname}`
```

=== Delete Deployment

```
kubectl delete -f deployment.yaml
```

kubectl create ingress demo-localhost --class=nginx \
  --rule=demo.localdev.me/*=demo:80

kubectl port-forward --namespace=my-dev service/hello-world-service 8888:8080


kubectl create ingress demo  --class=nginx --rule www.demo.io/=hello-world-service:8080

kubectl delete -A ValidatingWebhookConfiguration ingress-nginx-admission

kubectl port-forward --namespace=my-dev service/ingress-nginx-controller 80:80